import {
  TrendingUp,
  Calendar,
  MessageSquare,
  ListChecks,
  Mail,
  UserPlus,
  FileText,
  LifeBuoy,
  Settings,
  Megaphone,
  Users,
} from "lucide-react";

interface WorkflowTemplateStep {
  id: string;
  name: string;
  type: "trigger" | "action" | "condition" | "delay";
  description: string;
  config?: Record<string, unknown>;
  timeout_ms?: number;
  retries?: number;
  on_failure?: "continue" | "stop" | "skip";
}

export interface WorkflowTemplate {
  id: string;
  name: string;
  description: string;
  category: "sales" | "content" | "support" | "operations" | "marketing" | "hr";
  icon: typeof TrendingUp;
  color: string;
  steps: WorkflowTemplateStep[];
  popularity: number;
  estimatedSetup: string;
  trigger_type: "manual" | "scheduled" | "webhook" | "event";
  trigger_config?: Record<string, unknown>;
}

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: "lead-qualification",
    name: "Lead Qualification Pipeline",
    description:
      "Automatically qualify inbound leads based on form data and CRM history.",
    category: "sales",
    icon: TrendingUp,
    color: "text-green-500",
    trigger_type: "event",
    trigger_config: { event_type: "contact.created" },
    steps: [
      {
        id: "trigger-1",
        name: "New Lead Trigger",
        type: "trigger",
        description: "When a new contact is created",
      },
      {
        id: "action-1",
        name: "Score Lead",
        type: "action",
        description:
          "Calculate lead score based on company size, role, engagement",
        config: { command: "calculate_lead_score" },
        timeout_ms: 30000,
        retries: 1,
        on_failure: "stop",
      },
      {
        id: "condition-1",
        name: "Check Score Threshold",
        type: "condition",
        description: "If score >= 70",
        config: { expression: "lead_score >= 70" },
        timeout_ms: 5000,
        retries: 0,
        on_failure: "stop",
      },
      {
        id: "action-2",
        name: "Assign to Sales Rep",
        type: "action",
        description: "Route to appropriate sales rep",
        config: { command: "assign_sales_rep" },
        timeout_ms: 15000,
        retries: 1,
        on_failure: "continue",
      },
      {
        id: "action-3",
        name: "Send Welcome Email",
        type: "action",
        description: "Send personalized welcome sequence",
        config: { command: "send_email", template: "welcome" },
        timeout_ms: 20000,
        retries: 2,
        on_failure: "continue",
      },
    ],
    popularity: 5,
    estimatedSetup: "3 min",
  },
  {
    id: "blog-scheduling",
    name: "Blog Post Scheduling & Promotion",
    description:
      "Schedule blog posts and automatically promote across social channels.",
    category: "content",
    icon: Calendar,
    color: "text-blue-500",
    trigger_type: "scheduled",
    trigger_config: { cron: "0 9 * * *" },
    steps: [
      {
        id: "trigger-1",
        name: "Scheduled Publish",
        type: "trigger",
        description: "When a blog post publish date arrives",
      },
      {
        id: "action-1",
        name: "Publish Post",
        type: "action",
        description: "Set post status to published",
        config: { command: "publish_blog_post" },
        timeout_ms: 30000,
        retries: 1,
        on_failure: "stop",
      },
      {
        id: "delay-1",
        name: "Wait 1 Hour",
        type: "delay",
        description: "Wait for post to be indexed",
        config: { delay_ms: 3600000 },
        timeout_ms: 3610000,
        retries: 0,
        on_failure: "continue",
      },
      {
        id: "action-2",
        name: "Post to Social",
        type: "action",
        description: "Share on connected social accounts",
        config: { command: "share_to_social" },
        timeout_ms: 30000,
        retries: 2,
        on_failure: "continue",
      },
      {
        id: "action-3",
        name: "Notify Team",
        type: "action",
        description: "Send notification to content team",
        config: { command: "send_notification", channel: "content" },
        timeout_ms: 10000,
        retries: 1,
        on_failure: "continue",
      },
    ],
    popularity: 4,
    estimatedSetup: "2 min",
  },
  {
    id: "nps-followup",
    name: "NPS Detractor Follow-up",
    description:
      "Automatically follow up with customers who leave negative NPS scores.",
    category: "support",
    icon: MessageSquare,
    color: "text-yellow-500",
    trigger_type: "event",
    trigger_config: { event_type: "nps.response_received" },
    steps: [
      {
        id: "trigger-1",
        name: "NPS Response",
        type: "trigger",
        description: "When new NPS survey response received",
      },
      {
        id: "condition-1",
        name: "Check Score",
        type: "condition",
        description: "If NPS score <= 6 (detractor)",
        config: { expression: "nps_score <= 6" },
        timeout_ms: 5000,
        retries: 0,
        on_failure: "stop",
      },
      {
        id: "action-1",
        name: "Create Task",
        type: "action",
        description: "Create follow-up task for success team",
        config: { command: "create_task", team: "success" },
        timeout_ms: 15000,
        retries: 1,
        on_failure: "continue",
      },
      {
        id: "action-2",
        name: "Send Apology Email",
        type: "action",
        description: "Send personalized follow-up",
        config: { command: "send_email", template: "nps_followup" },
        timeout_ms: 20000,
        retries: 2,
        on_failure: "continue",
      },
      {
        id: "action-3",
        name: "Alert Manager",
        type: "action",
        description: "Notify account manager",
        config: { command: "send_alert", role: "account_manager" },
        timeout_ms: 10000,
        retries: 1,
        on_failure: "continue",
      },
    ],
    popularity: 5,
    estimatedSetup: "2 min",
  },
  {
    id: "daily-standup",
    name: "Daily Standup Summary",
    description:
      "Compile daily task activity and send a morning team briefing.",
    category: "operations",
    icon: ListChecks,
    color: "text-purple-500",
    trigger_type: "scheduled",
    trigger_config: { cron: "0 9 * * 1-5" },
    steps: [
      {
        id: "trigger-1",
        name: "Daily Schedule",
        type: "trigger",
        description: "Every weekday at 9:00 AM",
      },
      {
        id: "action-1",
        name: "Gather Updates",
        type: "action",
        description: "Query tasks completed/in-progress/blocked",
        config: { command: "gather_task_updates" },
        timeout_ms: 30000,
        retries: 1,
        on_failure: "stop",
      },
      {
        id: "action-2",
        name: "Generate Summary",
        type: "action",
        description: "AI-generate concise daily brief",
        config: { command: "generate_summary", model: "gpt-4" },
        timeout_ms: 45000,
        retries: 1,
        on_failure: "stop",
      },
      {
        id: "action-3",
        name: "Send to Team",
        type: "action",
        description: "Email/notify team channel",
        config: { command: "send_notification", channel: "team" },
        timeout_ms: 15000,
        retries: 2,
        on_failure: "continue",
      },
    ],
    popularity: 4,
    estimatedSetup: "2 min",
  },
  {
    id: "campaign-automation",
    name: "Email Campaign Drip Sequence",
    description: "Multi-step email drip campaign with engagement tracking.",
    category: "marketing",
    icon: Mail,
    color: "text-pink-500",
    trigger_type: "event",
    trigger_config: { event_type: "subscriber.joined" },
    steps: [
      {
        id: "trigger-1",
        name: "Subscriber Signup",
        type: "trigger",
        description: "When new subscriber joins list",
      },
      {
        id: "action-1",
        name: "Send Welcome",
        type: "action",
        description: "Send welcome email (day 0)",
        config: { command: "send_email", template: "welcome_day_0" },
        timeout_ms: 20000,
        retries: 2,
        on_failure: "stop",
      },
      {
        id: "delay-1",
        name: "Wait 3 Days",
        type: "delay",
        description: "Wait for engagement",
        config: { delay_ms: 259200000 },
        timeout_ms: 259210000,
        retries: 0,
        on_failure: "continue",
      },
      {
        id: "condition-1",
        name: "Check Opens",
        type: "condition",
        description: "If welcome email was opened",
        config: { expression: "email_opened == true" },
        timeout_ms: 5000,
        retries: 0,
        on_failure: "continue",
      },
      {
        id: "action-2",
        name: "Send Tutorial",
        type: "action",
        description: "Send getting-started tutorial",
        config: { command: "send_email", template: "tutorial_day_3" },
        timeout_ms: 20000,
        retries: 2,
        on_failure: "continue",
      },
      {
        id: "delay-2",
        name: "Wait 7 Days",
        type: "delay",
        description: "Wait for adoption",
        config: { delay_ms: 604800000 },
        timeout_ms: 604810000,
        retries: 0,
        on_failure: "continue",
      },
      {
        id: "action-3",
        name: "Send Case Study",
        type: "action",
        description: "Share customer success story",
        config: { command: "send_email", template: "case_study_day_10" },
        timeout_ms: 20000,
        retries: 2,
        on_failure: "continue",
      },
    ],
    popularity: 4,
    estimatedSetup: "5 min",
  },
  {
    id: "onboarding-checklist",
    name: "New Employee Onboarding",
    description:
      "Automated onboarding checklist with task assignments and reminders.",
    category: "hr",
    icon: UserPlus,
    color: "text-cyan-500",
    trigger_type: "event",
    trigger_config: { event_type: "employee.created" },
    steps: [
      {
        id: "trigger-1",
        name: "New Hire Added",
        type: "trigger",
        description: "When new employee record created",
      },
      {
        id: "action-1",
        name: "Create Tasks",
        type: "action",
        description: "Generate onboarding task checklist",
        config: { command: "create_onboarding_tasks" },
        timeout_ms: 30000,
        retries: 1,
        on_failure: "stop",
      },
      {
        id: "action-2",
        name: "Assign Buddy",
        type: "action",
        description: "Auto-assign onboarding buddy",
        config: { command: "assign_onboarding_buddy" },
        timeout_ms: 15000,
        retries: 1,
        on_failure: "continue",
      },
      {
        id: "action-3",
        name: "Send Welcome Pack",
        type: "action",
        description: "Email welcome info and credentials",
        config: { command: "send_email", template: "employee_welcome" },
        timeout_ms: 20000,
        retries: 2,
        on_failure: "continue",
      },
      {
        id: "action-4",
        name: "Schedule Check-ins",
        type: "action",
        description: "Create 30/60/90 day check-in tasks",
        config: { command: "schedule_checkin_tasks" },
        timeout_ms: 15000,
        retries: 1,
        on_failure: "continue",
      },
    ],
    popularity: 3,
    estimatedSetup: "3 min",
  },
];

export const WORKFLOW_CATEGORIES = [
  { id: "sales", label: "Sales", icon: TrendingUp },
  { id: "content", label: "Content", icon: FileText },
  { id: "support", label: "Support", icon: LifeBuoy },
  { id: "operations", label: "Operations", icon: Settings },
  { id: "marketing", label: "Marketing", icon: Megaphone },
  { id: "hr", label: "HR", icon: Users },
] as const;
