import fs from 'node:fs';
import { createHash } from 'node:crypto';
const root=new URL('../../',import.meta.url);
export const guides=JSON.parse(fs.readFileSync(new URL('src/data/territories/guides.json',root),'utf8'));
const profiles=JSON.parse(fs.readFileSync(new URL('src/data/territories/profiles.json',root),'utf8'));
export const origin='https://mejohnc.org';
export const version='1.0.0';
export const revision=createHash('sha256').update(JSON.stringify({guides,profiles})).update(fs.readFileSync(new URL('./model.mjs',import.meta.url))).digest('hex').slice(0,12);
export const projects={portfolio:'Portfolio', 'internal-tool':'Internal tool',store:'Store',publication:'Publication'};
const names={'neo-frutiger-aero':'Neo Frutiger Aero','retro-y2k':'Y2K','bento-box':'Bento Box','wabi-sabi':'Wabi-Sabi','neo-brutalism':'Neo-Brutalism','mid-century':'Mid-Century','dark-academia':'Dark Academia'};
const luminance=hex=>hex.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4).reduce((a,x,i)=>a+x*[.2126,.7152,.0722][i],0);
export const contrast=(a,b)=>(Math.max(luminance(a),luminance(b))+.05)/(Math.min(luminance(a),luminance(b))+.05);
const ink=surface=>contrast(surface,'#000000')>=contrast(surface,'#ffffff')?'#000000':'#ffffff';
export const commonChecks=[
 'Keyboard users can reach and activate navigation, filters, forms, and primary actions in reading order.',
 'Body text is at least 16px in this recipe, with visible focus and solid text surfaces.',
 'Normal text has at least 4.5:1 contrast; essential control boundaries and focus indicators remain distinguishable.',
 'At 390px wide and at 200% zoom, content reflows without hiding labels or actions.',
 'Errors identify the field and explain a correction; success confirms the actual result.',
 'Artwork has an appropriate text alternative; decorative artwork does not replace labels.',
 'No entrance delay, autoplay, or motion is required to read or operate the page.'
];
export const styles=Object.entries(guides).map(([id,d])=>{
 const profile=profiles[id];if(!profile)throw Error(`Missing profile ${id}`);
 const name=names[id]||id.split('-').map(s=>s[0].toUpperCase()+s.slice(1)).join(' ');
 const hard=['hard','pixel','grid'].includes(profile.treatment), ornate=profile.treatment==='ornate';
 const radius=hard?'0px':profile.treatment==='soft'?'20px':ornate?'2px':'8px';
 const color={surface:d.palette.surface,text:ink(d.palette.surface),accent:d.palette.accent,onAccent:ink(d.palette.accent),border:ink(d.palette.surface)};
 const family=d.type==='serif'?'Georgia, serif':d.type==='mono'?'ui-monospace, Menlo, Consolas, monospace':'system-ui, sans-serif';
 const tokens={schemaVersion:version,revision,styleId:id,name,scope:'Base UI tokens for a contemporary web adaptation. The example stylesheet adds style-specific composition, display typography, and decorative colors; inspect it for the complete visual treatment.',color,typography:{display:{family,size:'36px',maxSize:'52px',weight:600,lineHeight:1.15,textTransform:profile.treatment==='hard'?'uppercase':'none'},heading:{family,size:'24px',weight:600,lineHeight:1.3},body:{family:'system-ui, sans-serif',size:'16px',weight:400,lineHeight:1.65},caption:{family:'system-ui, sans-serif',size:'14px',weight:400,lineHeight:1.5}},spacing:{unit:'4px',control:'12px',section:profile.density==='compact'?'24px':'40px',page:profile.density==='compact'?'24px':'40px'},border:{width:hard?'2px':'1px',radius},shadow:profile.treatment==='hard'?`4px 4px 0 ${color.text}`:'none',layout:{navigationVariants:['top','sidebar','tabs'],previewWidths:{mobile:390,tablet:820,desktop:1440},readingMeasure:'65ch',collapseAt:'760px',minimumControlHeight:'44px'},motion:{duration:'0ms',reducedMotion:'No movement required'},decoration:{treatment:profile.treatment,scope:'Decorative layer only; retain semantic reading order.'}};
 const checks=[...d.steps.map(x=>`Confirm: ${x.toLowerCase()}.`),`Review specifically for: ${d.avoid}`, ...commonChecks];
 const path=`/territories/${id}/`;
 return {id,name,...d,profile,tokens,checks,links:{page:path,guide:path+'guide.md',brief:path+'brief.md',tokens:path+'tokens.json',checks:path+'checklist.md',example:path+'example/',versionedGuide:`/territories/v1/${id}/guide.md`,versionedTokens:`/territories/v1/${id}/tokens.json`}};
});
export const catalog={schemaVersion:version,revision,title:'Territories',description:'50 visual directions with practical web adaptations. Selection preferences are editorial suggestions, not objective rankings.',projects,links:{instructions:'/territories/agent.md',schema:'/territories/schema.json',skill:'/territories/skill/SKILL.md',compare:'/territories/compare/'},styles:styles.map(({id,name,overview,cues,profile,links})=>({id,name,overview,cues,profile,links}))};
export const guideMarkdown=s=>`# ${s.name}\n\nSchema: ${version} · Content revision: ${revision}\nResource base: ${origin} (or the preview host used to obtain this file).\n\n${s.overview}\n\n## Visual family\n${s.timeMachine.family}${s.timeMachine.period?` · ${s.timeMachine.period}`:''}. ${s.timeMachine.classification}\n\n## Visual cues\n${s.cues.map(x=>'- '+x).join('\n')}\n\n## Build it\n${s.steps.map((x,i)=>`${i+1}. ${x}.`).join('\n')}\n\n## Example\n${s.example}\n\n## Typography\n${s.typeAdvice}\n\n## Practical consequences\n- Starting projects: ${s.profile.projects.map(p=>projects[p]).join(', ')}. These are suggestions, not restrictions.\n- Reading/layout: ${s.profile.density}; ${s.profile.tone} visual emphasis.\n- Asset work: ${s.profile.imagery}\n- Complexity: ${s.profile.effort}. ${effortText(s.profile.effort)}\n\n## Limits\n${s.avoid}\n\n## Reading the collected reference board\n${s.referenceNote}\n\n## Context\n${s.context}. The recipe is a modern web adaptation.\n${s.source?`[${s.source.label}](${s.source.url})`:'No single inventor or exact founding date is asserted for this interpretation.'}\n\n## Implementation files\n${Object.entries(s.links).map(([k,v])=>`- [${k}](${v})`).join('\n')}\n`;
export function effortText(level){return {low:'Mostly standard CSS; imagery may still need preparation.',medium:'Allow time for a coherent decorative or image layer and responsive checks.',high:'Custom artwork or lettering is central to the full expression.'}[level];}
export const briefMarkdown=s=>`# Build brief: ${s.name}\n\nResource base: ${origin} (or the preview host used to obtain this file).\n\nUse this direction within the user’s requested project and existing design constraints.\n\n## Illustrative use case, not project requirements\n${s.example}\n\n${s.overview}\n\n## Essential cues\n${s.cues.map(x=>'- '+x).join('\n')}\n\n## Recipe\n${s.steps.map(x=>'- '+x+'.').join('\n')}\n\n## Optional decoration\n${s.profile.imagery}\n\n## Avoid\n${s.avoid}\n\n## Values and validation\nRead [tokens](${s.links.tokens}) and [acceptance checklist](${s.links.checks}). Use [the working example](${s.links.example}) to inspect color roles, spacing, hierarchy, and interaction states. It is a UI translation, not a reproduction of historical art. Tokens describe the base UI; [example CSS](/territories/assets/example.css) contains the style-specific composition and decorative layer. Preview navigation with \`?navigation=top\`, \`?navigation=sidebar\`, or \`?navigation=tabs\`; combine with \`project\`. Use [Compare](/territories/compare/) for mobile (390 px), tablet (820 px), and desktop (1440 px) viewports.\n\n## Delivery\nPreserve real content and existing working behavior. Check keyboard, narrow layout, error, empty, and success states. Report any departures from this recipe with a reason. Do not claim to have inspected a preview or run checks that you could not access.\n\nSchema ${version}; revision ${revision}.\n`;
